# 査読スコアリング・システム.py  (revised, Revision 1)
# Blinded expert-evaluation toolkit  (Reviewer 1 #6)
#
# The previous version of this file contained HARD-CODED scores (e.g. B = 9.2 / 9.5 / 8.8) that
# were typed in by hand and then "evaluated" by keyword lookup; it did not measure anything and is
# withdrawn. None of its numbers is used in the revised manuscript.
#
# This replacement implements the blinded expert-evaluation protocol described in Appendix A of
# the revised manuscript (planned future work; NOT yet carried out):
#
#   python 査読スコアリング・システム.py blind   <dir_with_manuscripts>  <out_dir>
#       -> copies every manuscript to <out_dir>/M###.<ext> in a seeded random order, writes the
#          secret key (code -> original file / condition) to <out_dir>/_KEY_do_not_share.csv and an
#          empty rating sheet (ratings_template.csv) for the raters.
#
#   python 査読スコアリング・システム.py analyse <ratings.csv> <_KEY_do_not_share.csv>
#       -> per-condition means with bootstrap 95% CIs, Krippendorff's alpha (interval) per
#          criterion as inter-rater reliability, Mann-Whitney U tests between conditions, and a
#          radar chart (fig_expert_radar.png).
#
# Rating sheet columns: rater, code, originality, soundness, reproducibility, significance,
#                       already_known (0/1), confidence  (all criteria 1-5 Likert; rubric in the
#                       manuscript's Appendix A)

import csv
import os
import random
import shutil
import sys
from itertools import combinations

import numpy as np

CRITERIA = ["originality", "soundness", "reproducibility", "significance"]
BLIND_SEED = 4591240


FOOTER_MARKERS = ("Generated by", "INCOMPLETE - generation stopped", "Process Date:")


def _copy_without_footer(src, dst):
    """Copies a manuscript while removing generation footers that would reveal the condition
    (e.g. '*Generated by the proposed model ... hypothesis source = ga ...*')."""
    ext = os.path.splitext(src)[1].lower()
    if ext in (".md", ".txt"):
        lines = open(src, encoding="utf-8").read().split("\n")
        kept = [ln for ln in lines if not any(mk in ln for mk in FOOTER_MARKERS)]
        open(dst, "w", encoding="utf-8").write("\n".join(kept))
    elif ext == ".docx":
        from docx import Document
        doc = Document(src)
        for p in list(doc.paragraphs):
            if any(mk in p.text for mk in FOOTER_MARKERS):
                p._element.getparent().remove(p._element)
        doc.save(dst)
    else:                                   # PDFs cannot be edited reliably; check them manually
        shutil.copy(src, dst)


def blind(src_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    files = sorted(f for f in os.listdir(src_dir) if f.lower().endswith((".docx", ".md", ".pdf", ".txt")))
    rng = random.Random(BLIND_SEED)
    rng.shuffle(files)
    with open(os.path.join(out_dir, "_KEY_do_not_share.csv"), "w", newline="", encoding="utf-8") as k, \
            open(os.path.join(out_dir, "ratings_template.csv"), "w", newline="", encoding="utf-8") as t:
        kw, tw = csv.writer(k), csv.writer(t)
        kw.writerow(["code", "original_file", "condition"])
        tw.writerow(["rater", "code", *CRITERIA, "already_known", "confidence"])
        for i, f in enumerate(files, 1):
            code = f"M{i:03d}"
            _copy_without_footer(os.path.join(src_dir, f), os.path.join(out_dir, code + os.path.splitext(f)[1]))
            cond = f.split("_")[0]          # file names are expected to start with the condition label
            kw.writerow([code, f, cond])
            tw.writerow(["", code] + [""] * (len(CRITERIA) + 2))
    print(f"blinded {len(files)} manuscripts -> {out_dir}  (keep _KEY_do_not_share.csv away from raters)")


def krippendorff_alpha_interval(units):
    """units: list of lists of ratings for each item (missing values omitted)."""
    pairs_within, all_vals = [], []
    for u in units:
        if len(u) < 2:
            continue
        m = len(u)
        for a, b in combinations(u, 2):
            pairs_within.append(((a - b) ** 2) * 2 / (m - 1))
        all_vals.extend(u)
    n = len(all_vals)
    if n < 2 or not pairs_within:
        return float("nan")
    Do = sum(pairs_within) / n
    De = sum((a - b) ** 2 for a, b in combinations(all_vals, 2)) * 2 / (n * (n - 1))
    return 1 - Do / De if De > 0 else float("nan")


def analyse(ratings_csv, key_csv):
    from scipy import stats
    key = {r["code"]: r["condition"] for r in csv.DictReader(open(key_csv, encoding="utf-8"))}
    rows = [r for r in csv.DictReader(open(ratings_csv, encoding="utf-8")) if r["rater"]]
    conds = sorted(set(key.values()))
    rng = np.random.default_rng(0)
    means, tests = {}, []
    print("criterion        alpha   " + "  ".join(f"{c:>18}" for c in conds))
    for c in CRITERIA:
        by_item = {}
        for r in rows:
            if r[c]:
                by_item.setdefault(r["code"], []).append(float(r[c]))
        alpha = krippendorff_alpha_interval(list(by_item.values()))
        item_means = {code: np.mean(v) for code, v in by_item.items()}
        line = []
        for cond in conds:
            x = np.array([m for code, m in item_means.items() if key[code] == cond])
            if len(x) == 0:
                line.append(f"{'n/a':>18}")
                continue
            boots = rng.choice(x, (5000, len(x))).mean(1)
            means.setdefault(cond, []).append(x.mean())
            line.append(f"{x.mean():.2f} [{np.percentile(boots, 2.5):.2f},{np.percentile(boots, 97.5):.2f}]")
        print(f"{c:<15} {alpha:6.2f}   " + "  ".join(f"{s:>18}" for s in line))
        for a, b in combinations(conds, 2):
            xa = [m for code, m in item_means.items() if key[code] == a]
            xb = [m for code, m in item_means.items() if key[code] == b]
            if len(xa) > 1 and len(xb) > 1:
                u, p = stats.mannwhitneyu(xa, xb, alternative="two-sided")
                tests.append((c, a, b, u, p))
    # Holm correction over all criterion x condition-pair tests
    order = sorted(range(len(tests)), key=lambda i: tests[i][4])
    adj, running = [0.0] * len(tests), 0.0
    for rank, i in enumerate(order):
        running = max(running, (len(tests) - rank) * tests[i][4])
        adj[i] = min(1.0, running)
    print("\nMann-Whitney U tests (Holm-corrected):")
    for (c, a, b, u, p), pa in zip(tests, adj):
        print(f"    {c:<15} {a} vs {b}: U={u:.1f}, p={p:.4f}, p_Holm={pa:.4f}")
    radar(means)


def radar(means):
    import matplotlib.pyplot as plt
    ang = np.linspace(0, 2 * np.pi, len(CRITERIA), endpoint=False).tolist()
    ang += ang[:1]
    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))
    for cond, v in means.items():
        if len(v) != len(CRITERIA):
            continue
        ax.plot(ang, v + v[:1], linewidth=2, label=cond)
        ax.fill(ang, v + v[:1], alpha=0.15)
    ax.set_thetagrids(np.degrees(ang[:-1]), [c.capitalize() for c in CRITERIA])
    ax.set_ylim(1, 5)
    ax.legend(loc="upper right", bbox_to_anchor=(1.3, 1.1))
    ax.set_title("Blinded expert ratings (mean per condition)")
    fig.savefig("fig_expert_radar.png", dpi=200, bbox_inches="tight")
    print("saved fig_expert_radar.png")


if __name__ == "__main__":
    if len(sys.argv) >= 4 and sys.argv[1] == "blind":
        blind(sys.argv[2], sys.argv[3])
    elif len(sys.argv) >= 4 and sys.argv[1] == "analyse":
        analyse(sys.argv[2], sys.argv[3])
    else:
        print(__doc__ if __doc__ else "see header of this file for usage")
